name: 'Gitbook Action'

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_gitbook_plugins
      run: |
        npm install gitbook-cli  -g
        gitbook -v
        gitbook install
    - name: build_gitbook
      run: |
        gitbook build
    - name: push_to_pages
      run: |
        cd ./_book
        git init
        git config --local user.name "${{ secrets.GIT_NAME }}"
        git config --local user.email "${{ secrets.GIT_EMAIL }}"
        git add *
        git commit -m "update"
        git push --force  "https://${{ secrets.THE_GITHUB_TOKEN }}@${{ secrets.THE_GITHUB_REF }}" master:${{ secrets.RES_FOR_PAGES }}
        git push --force  "https://${{ secrets.THE_CODING_TOKEN }}@${{ secrets.THE_CODING_REF }}" master:${{ secrets.RES_FOR_CODING_PAGES }}
        git push --force  "https://${{ secrets.THE_GITHUB_TOKEN }}@${{ secrets.THE_MonoHelp_REF }}" master:${{ secrets.RES_FOR_PAGES }}
      env:
        CI: true
